language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
    secure: NCrQVlp1uMw/w5swNrXClQYLsceyQ69d9dLYh0pccO4SUVE/UFJXQoOEBKLnqu1Cqlgz7tpMTs2H/AYHXJaimyerVWhhczaXx2Hr5rlYOXfHOolo/pZ+DWiS4j69awnPORae8wDZHi+xZucULdQXa1EBtVrGO5AzU/Xq1Gg9cJK3uzJtze1odEjAHKgIKbdR4SQludAHFkTiCzbIDKwJRT2HwgSk9odrmGDCbU8xtLV2NzzGxPTvZG7KmLY8FSEtmVZDMuhTBNhtGOvZu+1QEMS0cngKn+aL1qhO3AZraBxpj74GNVwfeHN3aTnKXZ/nJHKuonKxjGMXCKMaGzyGwopA10U982oqjGYm4zENPkpRqAe1WaI4S2CTroEXHalGCZFIjPXga1z5Q4fng0FFdq96+RRjj9JFXgfngOk+Co+T+QriXbWjMqHKWf618qId1iri4l2b9BDkwSQ6JpGTBc2uOZ6YgNGhicwTHw5X1tlkLXXV+j2gR2xFa0lZGj96Oba12VPSpw5JaZ9n0N+Y0SnVx5SbzPnkFCv6DMYGrB3ynWT0b7bnSSj4tvwAoy5YglbmrxRluR/CYTmp+q+dad5am2FSspZGrAo5uYvKkPrc/cy1G2Rn+iyHNbT7WTgA5NVNn4QTGi15/3qwaTIXQqFSiYuj5PhP3hq7B9Uaxbo=
  app: duncan-noteful-v4
  on:
    repo: thinkful-ei19/duncan-noteful-v4
